---
# file: roles/node_exporter/tasks/main.yml

- name: Create node_exporter directory
  file:
    path: '/home/{{ ansible_user }}/node_exporter'
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: 0775

- name: Download and unarchive latest node_exporter release
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v0.16.0/node_exporter-0.16.0.linux-amd64.tar.gz
    dest: '/home/{{ ansible_user }}/node_exporter'
    remote_src: yes

- name: Create user node_exporter
  user:
    name: node_exporter
    create_home: no
    shell: /bin/false

- name: copy node_exporter binary
  copy:
    src: '/home/{{ ansible_user }}/node_exporter/node_exporter-0.16.0.linux-amd64/node_exporter'
    dest: /usr/local/bin
    remote_src: yes
    owner: node_exporter
    group: node_exporter
    mode: 0755

- name: Copy node_exporter configuration file
  copy:
    src: files/node_exporter.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 0644

- name: Remove temporary downloads
  file:
    path: '/home/{{ ansible_user }}/node_exporter/'
    state: absent

- name: Stop and disable node_exporter service
  systemd:
    name: node_exporter
    daemon_reload: yes
    enabled: no
    state: stopped
